### ISSUE TITLE
Unreachable code in semaphore.md

### ISSUE THREAD

**Issue by tommasodotNET** [crazybber/go-patterns#4]
In the semaphore pattern, the Release func has an unreachable return statement:

```
func (s *implementation) Release() error {
	select {
	case _ = <-s.sem:
		return nil
	case <-time.After(s.timeout):
		return ErrIllegalRelease
	}

	return nil
}
```

The last `return nil` will never be reached.

**Comment by crazybber** [comment]
fixed in https://github.com/crazybber/awesome-patterns/pull/5
