### ISSUE TITLE
Cascading Failures pattern not found

### ISSUE THREAD

**Issue by focusaurus** [crazybber/go-patterns#7]
Link from readme is broken

**Comment by crazybber** [comment]
@focusaurus could u provide a fix ？

**Comment by focusaurus** [comment]
I don't have the content that would go there, no. I was just trying to read it. I mean, I can send a PR to remove it from the README if you like but not sure how helpful that is.

**Comment by crazybber** [comment]
yes，I mean a “PR”, which can fix  link, if you are willing to .it will be nice help.
